// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5999.powerup.subsystems;

import org.usfirst.frc5999.powerup.RobotMap;
import org.usfirst.frc5999.powerup.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Elevator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX elevatorMotor = RobotMap.elevatorelevatorMotor;
    private final DigitalInput vaultPosSwitch = RobotMap.elevatorvaultPosSwitch;
    private final DigitalInput lowSwitchPosSwitch = RobotMap.elevatorlowSwitchPosSwitch;
    private final DigitalInput highSwitchPosSwitch = RobotMap.elevatorhighSwitchPosSwitch;
    private final DigitalInput lowScalePosSwitch = RobotMap.elevatorlowScalePosSwitch;
    private final DigitalInput highScalePosSwitch = RobotMap.elevatorhighScalePosSwitch;
    private final DigitalInput liftPointPosSwitch = RobotMap.elevatorliftPointPosSwitch;
    private final AnalogPotentiometer position_pot = RobotMap.elevatorposition_pot;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

